name: CI with Jfrog

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Login to Jfrog Artifactory (replace with your details)
      - name: setup Jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env: 
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      - name: Build maven
      #building package with jfrog cli maven 
        run: |
            jf mvn clean package
      - name: Upload build artifacts
        uses: jfrog/push-action@v3
        with:
          files: dist/**  # Replace with your artifact path
          artifactory: artifactory  # Name from login step 
          repo: ptfl1-maven-virtual   # Replace with your repository name